#!/bin/bash
source ~/.cmdtaggr/config.sh
homesys=$(df ~ | awk 'NR==2{print $1}')

case $1 in 
	help) 
		cat ~/.cmdtaggr/help.txt
		;;
	tui) 
		source ~/.cmdtaggr/interface.sh
		;;
	create)
		touch ~/.cmdtaggr/tags/$2
		tagname=$2
		shift 2
		for var in "$@"; do
		    inode=$(ls -li $var | awk 'NR==1{print $1}')
			echo $inode >> $tgdr/$tagname
		done
		;;
	list)
		ls ~/cmdtaggr/tags
	;;
	files)
		for line in $(cat $tgdr/$2); do
			  sudo debugfs -R "ncheck $line" $homesys >> ~/.cmdtaggr/fl 2> /dev/null
			done
		awk 'NR % 2 != 1{print $2}' ~/.cmdtaggr/fl
		rm ~/.cmdtaggr/fl
	;;
	add)
		tagname=$2
		shift 2
		for var in "$@"; do
		    inode=$(ls -li $var | awk 'NR==1{print $1}')
			echo $inode >> $tgdr/$tagname
		done
		;;
	remove)
		tagname=$2
		shift 2
		for var in "$@"; do
		    inode=$(ls -li $var | awk 'NR==1{print $1}')
			sed -i "/$inode/d" $tgdr/$tagname      
		done
	;;
	delete)
		rm $tgdr/$2\
	;;
	*)
		echo "Invalid input"
		echo "Run 'help' for usage information"
		;;
esac