#!/bin/bash
source ~/.cmdtaggr/config.sh
homesys=$(df ~ | awk 'NR==2{print $1}')
filesys=$(df -Th ~ | awk 'NR==2{print $2}')

case $1 in 
	help) 
		cat ~/.cmdtaggr/help.txt
	;;
	tui) 
		source ~/.cmdtaggr/interface.sh
	;;
	create)
		touch ~/.cmdtaggr/tags/$2
		tagname=$2
		shift 2
		for var in "$@"; do
		    inode=$(ls -li $var | awk 'NR==1{print $1}')
			echo $inode >> $tgdr/$tagname
		done
	;;
	list)
		ls -p ~/.cmdtaggr/tags | grep -v /
	;;
	files)
		for line in $(cat $tgdr/$2); do
			  sudo debugfs -R "ncheck $line" $homesys >> ~/.cmdtaggr/fl 2> /dev/null
			done
		awk 'NR % 2 != 1{print $2}' ~/.cmdtaggr/fl
		if [[ $keepfl == 0 ]]; then 
			rm ~/.cmdtaggr/fl
		elif [[ $keepfl == 1 ]]; then
			mv ~/.cmdtaggr/fl $tgdr/fl/$2
		else
			rm ~/.cmdtaggr/fl 
			echo The keepfl value in config.sh is improperly configured.
			echo Please ensure that it is set to either 1 or 0
			echo By default, the file has been removed.
		fi
	;;
	search) 
			for line in $(cat $tgdr/$2); do
			    sudo debugfs -R "ncheck $line" $homesys >> ~/.cmdtaggr/fl 2> /dev/null
			done
			awk 'NR % 2 != 1{print $2}' ~/.cmdtaggr/fl >> ~/.cmdtaggr/fls
			rm ~/.cmdtaggr/fl
			grep "$3" ~/.cmdtaggr/fls
	;;
	add)
		tagname=$2
		shift 2
		for var in "$@"; do
		    inode=$(ls -li $var | awk 'NR==1{print $1}')
			echo $inode >> $tgdr/$tagname
		done
	;;
	remove)
		tagname=$2
		shift 2
		for var in "$@"; do
		    inode=$(ls -li $var | awk 'NR==1{print $1}')
			sed -i "/$inode/d" $tgdr/$tagname      
		done
	;;
	delete)
		rm $tgdr/$2
	;;
	*)
		echo "Invalid input"
		echo "Run 'help' for usage information"
	;;
esac